# Flask config
TESTING = False
SECRET_KEY = "Qemoyjif4ZNygi4UHbg0sxtRiXA4i0FYTRx762cB9zED4XFMF9"
PERMANENT_SESSION_LIFETIME = 180
JSONIFY_PRETTYPRINT_REGULAR = True
UPLOAD_FOLDER = "/tmp"
ALLOWED_EXTENSIONS = {"csv"}
LOG_FILE = "../sms-log.txt"
